(cl:defpackage usv_msg-srv
  (:use )
  (:export
   "CLASSIFYBUOY"
   "<CLASSIFYBUOY-REQUEST>"
   "CLASSIFYBUOY-REQUEST"
   "<CLASSIFYBUOY-RESPONSE>"
   "CLASSIFYBUOY-RESPONSE"
   "CLASSIFYPLACARD"
   "<CLASSIFYPLACARD-REQUEST>"
   "CLASSIFYPLACARD-REQUEST"
   "<CLASSIFYPLACARD-RESPONSE>"
   "CLASSIFYPLACARD-RESPONSE"
   "CLASSIFYSHAPE"
   "<CLASSIFYSHAPE-REQUEST>"
   "CLASSIFYSHAPE-REQUEST"
   "<CLASSIFYSHAPE-RESPONSE>"
   "CLASSIFYSHAPE-RESPONSE"
  ))

