; Auto-generated. Do not edit!


(cl:in-package usv_msg-msg)


;//! \htmlinclude DockFeedback.msg.html

(cl:defclass <DockFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:string
    :initform ""))
)

(cl:defclass DockFeedback (<DockFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DockFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DockFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name usv_msg-msg:<DockFeedback> is deprecated: use usv_msg-msg:DockFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <DockFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader usv_msg-msg:progress-val is deprecated.  Use usv_msg-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DockFeedback>) ostream)
  "Serializes a message object of type '<DockFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'progress))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DockFeedback>) istream)
  "Deserializes a message object of type '<DockFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'progress) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'progress) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DockFeedback>)))
  "Returns string type for a message object of type '<DockFeedback>"
  "usv_msg/DockFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DockFeedback)))
  "Returns string type for a message object of type 'DockFeedback"
  "usv_msg/DockFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DockFeedback>)))
  "Returns md5sum for a message object of type '<DockFeedback>"
  "4e8180fd8cffb84e555b1c648b3e7287")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DockFeedback)))
  "Returns md5sum for a message object of type 'DockFeedback"
  "4e8180fd8cffb84e555b1c648b3e7287")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DockFeedback>)))
  "Returns full string definition for message of type '<DockFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# FEEDBACK ---------------------~%string progress # Provides messages indicating progress in docking~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DockFeedback)))
  "Returns full string definition for message of type 'DockFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# FEEDBACK ---------------------~%string progress # Provides messages indicating progress in docking~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DockFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'progress))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DockFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DockFeedback
    (cl:cons ':progress (progress msg))
))
