
(cl:in-package :asdf)

(defsystem "usv_msg-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "Course" :depends-on ("_package_Course"))
    (:file "_package_Course" :depends-on ("_package"))
    (:file "DockAction" :depends-on ("_package_DockAction"))
    (:file "_package_DockAction" :depends-on ("_package"))
    (:file "DockActionFeedback" :depends-on ("_package_DockActionFeedback"))
    (:file "_package_DockActionFeedback" :depends-on ("_package"))
    (:file "DockActionGoal" :depends-on ("_package_DockActionGoal"))
    (:file "_package_DockActionGoal" :depends-on ("_package"))
    (:file "DockActionResult" :depends-on ("_package_DockActionResult"))
    (:file "_package_DockActionResult" :depends-on ("_package"))
    (:file "DockFeedback" :depends-on ("_package_DockFeedback"))
    (:file "_package_DockFeedback" :depends-on ("_package"))
    (:file "DockGoal" :depends-on ("_package_DockGoal"))
    (:file "_package_DockGoal" :depends-on ("_package"))
    (:file "DockResult" :depends-on ("_package_DockResult"))
    (:file "_package_DockResult" :depends-on ("_package"))
    (:file "Object" :depends-on ("_package_Object"))
    (:file "_package_Object" :depends-on ("_package"))
    (:file "ObjectArray" :depends-on ("_package_ObjectArray"))
    (:file "_package_ObjectArray" :depends-on ("_package"))
    (:file "Task" :depends-on ("_package_Task"))
    (:file "_package_Task" :depends-on ("_package"))
    (:file "VesselPath" :depends-on ("_package_VesselPath"))
    (:file "_package_VesselPath" :depends-on ("_package"))
    (:file "VesselWaypoint" :depends-on ("_package_VesselWaypoint"))
    (:file "_package_VesselWaypoint" :depends-on ("_package"))
    (:file "Waypoint" :depends-on ("_package_Waypoint"))
    (:file "_package_Waypoint" :depends-on ("_package"))
    (:file "WaypointReached" :depends-on ("_package_WaypointReached"))
    (:file "_package_WaypointReached" :depends-on ("_package"))
    (:file "WaypointRoute" :depends-on ("_package_WaypointRoute"))
    (:file "_package_WaypointRoute" :depends-on ("_package"))
  ))