# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from usv_msg/Course.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Course(genpy.Message):
  _md5sum = "0f1618d14a516cca02103ea76395704b"
  _type = "usv_msg/Course"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Command an absolute yaw and velocity.

# Yaw is specified in radians counter-clockwise from true east.
float32 yaw

# Velocity is specified in meters/s. Negative values correspond to reversing.
float32 speed

# If true, vessel will maintain station (speed ignored, yaw commanded)
bool keep_station

# If station keeping, need to keep heading aligned with station_yaw 
float32 station_yaw

# Distance from vessel to station, used for stationkeeping PID
float32 station_dist_x
float32 station_dist_y"""
  __slots__ = ['yaw','speed','keep_station','station_yaw','station_dist_x','station_dist_y']
  _slot_types = ['float32','float32','bool','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw,speed,keep_station,station_yaw,station_dist_x,station_dist_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Course, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw is None:
        self.yaw = 0.
      if self.speed is None:
        self.speed = 0.
      if self.keep_station is None:
        self.keep_station = False
      if self.station_yaw is None:
        self.station_yaw = 0.
      if self.station_dist_x is None:
        self.station_dist_x = 0.
      if self.station_dist_y is None:
        self.station_dist_y = 0.
    else:
      self.yaw = 0.
      self.speed = 0.
      self.keep_station = False
      self.station_yaw = 0.
      self.station_dist_x = 0.
      self.station_dist_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2fB3f().pack(_x.yaw, _x.speed, _x.keep_station, _x.station_yaw, _x.station_dist_x, _x.station_dist_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.yaw, _x.speed, _x.keep_station, _x.station_yaw, _x.station_dist_x, _x.station_dist_y,) = _get_struct_2fB3f().unpack(str[start:end])
      self.keep_station = bool(self.keep_station)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2fB3f().pack(_x.yaw, _x.speed, _x.keep_station, _x.station_yaw, _x.station_dist_x, _x.station_dist_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.yaw, _x.speed, _x.keep_station, _x.station_yaw, _x.station_dist_x, _x.station_dist_y,) = _get_struct_2fB3f().unpack(str[start:end])
      self.keep_station = bool(self.keep_station)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fB3f = None
def _get_struct_2fB3f():
    global _struct_2fB3f
    if _struct_2fB3f is None:
        _struct_2fB3f = struct.Struct("<2fB3f")
    return _struct_2fB3f
