# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from usv_msg/DockGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class DockGoal(genpy.Message):
  _md5sum = "1051aa2cfda5f1f9d590e13678b89bd2"
  _type = "usv_msg/DockGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# GOAL -------------------------
geometry_msgs/Pose bay_position   # Position of center of the desired docking bay
geometry_msgs/Pose dock_position  # Position of center of the dock
float32            dock_yaw       # Yaw that the vessel must maintain when entering

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['bay_position','dock_position','dock_yaw']
  _slot_types = ['geometry_msgs/Pose','geometry_msgs/Pose','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bay_position,dock_position,dock_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DockGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bay_position is None:
        self.bay_position = geometry_msgs.msg.Pose()
      if self.dock_position is None:
        self.dock_position = geometry_msgs.msg.Pose()
      if self.dock_yaw is None:
        self.dock_yaw = 0.
    else:
      self.bay_position = geometry_msgs.msg.Pose()
      self.dock_position = geometry_msgs.msg.Pose()
      self.dock_yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_14df().pack(_x.bay_position.position.x, _x.bay_position.position.y, _x.bay_position.position.z, _x.bay_position.orientation.x, _x.bay_position.orientation.y, _x.bay_position.orientation.z, _x.bay_position.orientation.w, _x.dock_position.position.x, _x.dock_position.position.y, _x.dock_position.position.z, _x.dock_position.orientation.x, _x.dock_position.orientation.y, _x.dock_position.orientation.z, _x.dock_position.orientation.w, _x.dock_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bay_position is None:
        self.bay_position = geometry_msgs.msg.Pose()
      if self.dock_position is None:
        self.dock_position = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.bay_position.position.x, _x.bay_position.position.y, _x.bay_position.position.z, _x.bay_position.orientation.x, _x.bay_position.orientation.y, _x.bay_position.orientation.z, _x.bay_position.orientation.w, _x.dock_position.position.x, _x.dock_position.position.y, _x.dock_position.position.z, _x.dock_position.orientation.x, _x.dock_position.orientation.y, _x.dock_position.orientation.z, _x.dock_position.orientation.w, _x.dock_yaw,) = _get_struct_14df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_14df().pack(_x.bay_position.position.x, _x.bay_position.position.y, _x.bay_position.position.z, _x.bay_position.orientation.x, _x.bay_position.orientation.y, _x.bay_position.orientation.z, _x.bay_position.orientation.w, _x.dock_position.position.x, _x.dock_position.position.y, _x.dock_position.position.z, _x.dock_position.orientation.x, _x.dock_position.orientation.y, _x.dock_position.orientation.z, _x.dock_position.orientation.w, _x.dock_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bay_position is None:
        self.bay_position = geometry_msgs.msg.Pose()
      if self.dock_position is None:
        self.dock_position = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.bay_position.position.x, _x.bay_position.position.y, _x.bay_position.position.z, _x.bay_position.orientation.x, _x.bay_position.orientation.y, _x.bay_position.orientation.z, _x.bay_position.orientation.w, _x.dock_position.position.x, _x.dock_position.position.y, _x.dock_position.position.z, _x.dock_position.orientation.x, _x.dock_position.orientation.y, _x.dock_position.orientation.z, _x.dock_position.orientation.w, _x.dock_yaw,) = _get_struct_14df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14df = None
def _get_struct_14df():
    global _struct_14df
    if _struct_14df is None:
        _struct_14df = struct.Struct("<14df")
    return _struct_14df
