// Generated by gencpp from file usv_msg/ClassifyPlacardResponse.msg
// DO NOT EDIT!


#ifndef USV_MSG_MESSAGE_CLASSIFYPLACARDRESPONSE_H
#define USV_MSG_MESSAGE_CLASSIFYPLACARDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_msg
{
template <class ContainerAllocator>
struct ClassifyPlacardResponse_
{
  typedef ClassifyPlacardResponse_<ContainerAllocator> Type;

  ClassifyPlacardResponse_()
    : label()
    , confidence(0.0)
    , centre_x(0)
    , success(false)  {
    }
  ClassifyPlacardResponse_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , confidence(0.0)
    , centre_x(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _centre_x_type;
  _centre_x_type centre_x;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifyPlacardResponse_

typedef ::usv_msg::ClassifyPlacardResponse_<std::allocator<void> > ClassifyPlacardResponse;

typedef boost::shared_ptr< ::usv_msg::ClassifyPlacardResponse > ClassifyPlacardResponsePtr;
typedef boost::shared_ptr< ::usv_msg::ClassifyPlacardResponse const> ClassifyPlacardResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator1> & lhs, const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.confidence == rhs.confidence &&
    lhs.centre_x == rhs.centre_x &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator1> & lhs, const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16e1e649d067a97acc4d232e511729eb";
  }

  static const char* value(const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16e1e649d067a97aULL;
  static const uint64_t static_value2 = 0xcc4d232e511729ebULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msg/ClassifyPlacardResponse";
  }

  static const char* value(const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"float32 confidence\n"
"int32 centre_x\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.confidence);
      stream.next(m.centre_x);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifyPlacardResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msg::ClassifyPlacardResponse_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "centre_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.centre_x);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSG_MESSAGE_CLASSIFYPLACARDRESPONSE_H
