// Generated by gencpp from file usv_msg/VesselWaypoint.msg
// DO NOT EDIT!


#ifndef USV_MSG_MESSAGE_VESSELWAYPOINT_H
#define USV_MSG_MESSAGE_VESSELWAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace usv_msg
{
template <class ContainerAllocator>
struct VesselWaypoint_
{
  typedef VesselWaypoint_<ContainerAllocator> Type;

  VesselWaypoint_()
    : pose()
    , tolerance(0.0)  {
    }
  VesselWaypoint_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , tolerance(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _tolerance_type;
  _tolerance_type tolerance;





  typedef boost::shared_ptr< ::usv_msg::VesselWaypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msg::VesselWaypoint_<ContainerAllocator> const> ConstPtr;

}; // struct VesselWaypoint_

typedef ::usv_msg::VesselWaypoint_<std::allocator<void> > VesselWaypoint;

typedef boost::shared_ptr< ::usv_msg::VesselWaypoint > VesselWaypointPtr;
typedef boost::shared_ptr< ::usv_msg::VesselWaypoint const> VesselWaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msg::VesselWaypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msg::VesselWaypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msg::VesselWaypoint_<ContainerAllocator1> & lhs, const ::usv_msg::VesselWaypoint_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.tolerance == rhs.tolerance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msg::VesselWaypoint_<ContainerAllocator1> & lhs, const ::usv_msg::VesselWaypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msg::VesselWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msg::VesselWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msg::VesselWaypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a86a362d03a0b4e7c7a4ba71dd826bc6";
  }

  static const char* value(const ::usv_msg::VesselWaypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa86a362d03a0b4e7ULL;
  static const uint64_t static_value2 = 0xc7a4ba71dd826bc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msg/VesselWaypoint";
  }

  static const char* value(const ::usv_msg::VesselWaypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Desired pose of the waypoint\n"
"geometry_msgs/Pose pose\n"
"# Tolerance on the waypoint\n"
"float64 tolerance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::usv_msg::VesselWaypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VesselWaypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msg::VesselWaypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msg::VesselWaypoint_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "tolerance: ";
    Printer<double>::stream(s, indent + "  ", v.tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSG_MESSAGE_VESSELWAYPOINT_H
