// Auto-generated. Do not edit!

// (in-package usv_msg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class DockGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.bay_position = null;
      this.dock_position = null;
      this.dock_yaw = null;
    }
    else {
      if (initObj.hasOwnProperty('bay_position')) {
        this.bay_position = initObj.bay_position
      }
      else {
        this.bay_position = new geometry_msgs.msg.Pose();
      }
      if (initObj.hasOwnProperty('dock_position')) {
        this.dock_position = initObj.dock_position
      }
      else {
        this.dock_position = new geometry_msgs.msg.Pose();
      }
      if (initObj.hasOwnProperty('dock_yaw')) {
        this.dock_yaw = initObj.dock_yaw
      }
      else {
        this.dock_yaw = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockGoal
    // Serialize message field [bay_position]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.bay_position, buffer, bufferOffset);
    // Serialize message field [dock_position]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.dock_position, buffer, bufferOffset);
    // Serialize message field [dock_yaw]
    bufferOffset = _serializer.float32(obj.dock_yaw, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockGoal
    let len;
    let data = new DockGoal(null);
    // Deserialize message field [bay_position]
    data.bay_position = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [dock_position]
    data.dock_position = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    // Deserialize message field [dock_yaw]
    data.dock_yaw = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 116;
  }

  static datatype() {
    // Returns string type for a message object
    return 'usv_msg/DockGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1051aa2cfda5f1f9d590e13678b89bd2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # GOAL -------------------------
    geometry_msgs/Pose bay_position   # Position of center of the desired docking bay
    geometry_msgs/Pose dock_position  # Position of center of the dock
    float32            dock_yaw       # Yaw that the vessel must maintain when entering
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockGoal(null);
    if (msg.bay_position !== undefined) {
      resolved.bay_position = geometry_msgs.msg.Pose.Resolve(msg.bay_position)
    }
    else {
      resolved.bay_position = new geometry_msgs.msg.Pose()
    }

    if (msg.dock_position !== undefined) {
      resolved.dock_position = geometry_msgs.msg.Pose.Resolve(msg.dock_position)
    }
    else {
      resolved.dock_position = new geometry_msgs.msg.Pose()
    }

    if (msg.dock_yaw !== undefined) {
      resolved.dock_yaw = msg.dock_yaw;
    }
    else {
      resolved.dock_yaw = 0.0
    }

    return resolved;
    }
};

module.exports = DockGoal;
